### ISSUE TITLE
艾琳可以参考一下麻兜

### ISSUE THREAD

**Issue by DaiShengSheng** [yuyumoko/mahjong-hand-guess#1]
麻兜：https://mahjong-handle.update.sh/
蓝色为位置正确，橘色为手牌中存在但位置不正确）

**Comment by yuyumoko** [comment]
啊?  现在这个不就是这个吗 只不过是牌背颜色变化

**Comment by DaiShengSheng** [comment]
嘛，还是要区分一下橘色和蓝色，要不猜着猜着就蒙了）

**Comment by yuyumoko** [comment]
你是说不明显是吗

**Comment by DaiShengSheng** [comment]
确实，现在的话位置正确和存在但位置不正确是相同的颜色，还是挺容易出错的

**Comment by yuyumoko** [comment]
不是啊.. 位置正确的是 蓝色的牌背 ,  存在且位置不正确的是橙色牌背

**Comment by DaiShengSheng** [comment]
我超，这个牌背，你不说我还没看出来....确实不太明显

**Comment by yuyumoko** [comment]
这..
